<?php ///[i18n:Long Text Translation]
///such as: 'Sorry, we are unable to reset password ...' => 'Sorry, we are unable to reset password for the provided email address.',

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [

	///\vendor\yongtiger\yii2-article\src\models\Content.php
	'ID' => 'ID',
	'Body' => '内容',
	'Created By' => '创建者',
	'Updated By' => '更新者',
	'Created At' => '创建时间',
	'Updated At' => '更新时间',

	///\vendor\yongtiger\yii2-article\src\models\Post.php
	'Category ID' => '目录ID',
	'Title' => '标题',
	'Summary' => '简介',
	'Content ID' => '内容ID',
	'User ID' => '用户ID',
	'Status' => '状态',
	'Tag' => '标签',

	///\vendor\yongtiger\yii2-article\src\models\Tag.php
	'Name' => '名称',
	'Frequency' => '使用频率',

	///\vendor\yongtiger\yii2-article\src\views\post\_form.php
	'Create' => '创建',
	'Update' => '更新',
	'STATUS_DELETE' => '已删除',
	'STATUS_MODERATE' => '正在审核',
	'STATUS_ACTIVE' => '通过审核',
	'(Select ...)' => '(请选择 ...)',

	///\vendor\yongtiger\yii2-article\src\views\post\_search.php
	'Search' => '搜索',
	'Reset' => '重置',

	///\vendor\yongtiger\yii2-article\src\views\post\create.php
	'Create Post' => '创建文章',
	'Posts' => '文章列表',

	///\vendor\yongtiger\yii2-article\src\views\post\update.php
	'Update Post' => '更新文章',

	///\vendor\yongtiger\yii2-article\src\views\post\view.php
	'Delete' => '删除',
	'Are you sure you want to delete this item?' => '您确定要删除该项吗？',
	'Content' => '正文',
	'Username' => '用户名',
	'Status' => '状态',

];
